language: perl

env:
    - QR_CONTENT=1

perl:
    - "5.28"
    - "5.20"

notifications:
    recipients:
        - mirko@westermeier.de
    email:
        on_success: always
        on_failure: always
